# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: restato's memo
email: direcision@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: restato
minimal_mistakes_skin: dark # neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "restato"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "just try your hardest."
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/direcision?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/restato"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/direcision?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/restato"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# google_site_verification: 0GLTtjarMTr8NsaJaP-z0tbHPycvu_rOoQykr81BL0o # fill in to your verification string

# google_analytics:
#   id: G-CJKYE91FQM # fill in your Google Analytics ID
#   # Google Analytics pageviews report settings
#   pv:
#     proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
#     cache_path:   

# comments:
#   active: giscus         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
#   # The active options are as follows:
#   disqus:
#     shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
#   # utterances settings › https://utteranc.es/
#   utterances:
#     repo:         # <gh-username>/<repo>
#     issue_term:   # < url | pathname | title | ...>
#   # Giscus options › https://giscus.app
#   giscus:
#     repo: restato/blog-comments       # <gh-username>/<repo>
#     repo_id:
#     category:
#     category_id:
#     mapping:           # optional, default to 'pathname'
#     input_position:    # optional, default to 'bottom'
#     lang:         